on:
  push:
    branches:
      - main

jobs:
  release:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Git
        run: |
          git config user.name "GitHub Bot"
          git config user.email "gituser@example.com"

      - name: Files verification
        run: echo (ls ./examples -p | grep -v / | tr '\n' ',')

      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: "16.x"
      #     cache: 'yarn'
      # - name: Install dependencies
      #   run: yarn install --frozen-lockfile --prefer-offline


      # - name: Deploy
      #   run: yarn nx run-many --target=deploy --all --exclude=$(ls -p ./examples | grep -v / | tr '\n' ',') --dry-run

# jobs:
#   release:
#     name: Release
#     runs-on: ubuntu-latest

#     steps:

#     - name: Release
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#       run: yarn exec semantic-release
#     - name: set env
#       run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
#     # Drafts your next Release notes as Pull Requests are merged into "main"
#     - name: Draft Release notes
#       id: draft-release-notes
#       uses: release-drafter/release-drafter@v5
#       if: github.ref == 'refs/heads/main'
#       with:
#         config-name: release-drafter.yml
#         publish: true
#         tag: ${{ env.TAG }}
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

